### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by geekzxiang** [kidGuo/WeChatUI_ArkUI#1]
咋这么卡呢

**Comment by kidGuo** [comment]
preview模式吗？
 DevEco-Studio对设备有一定要求，推荐真机查看

**Comment by geekzxiang** [comment]
不是ide卡，是程序装到手机上卡，我P40，切下tab卡好久

**Comment by kidGuo** [comment]
> 不是ide卡，是程序装到手机上卡，我P40，切下tab卡好久

可以说下hos系统版本，具体切哪个tab吗？

**Comment by geekzxiang** [comment]
Harmony0S4.0   不知道是什么问题，我从官网下载的demo运行也非常卡

**Comment by songxing10000** [comment]
大佬
